
FROM golang:1.25-alpine AS builder

WORKDIR /app
# COPY go.mod go.sum ./
COPY go.mod ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o app

FROM gcr.io/distroless/base-debian12

WORKDIR /app
COPY --from=builder /app/app /app/app

EXPOSE 8080
USER nonroot:nonroot

CMD ["/app/app"]
